apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: of1-grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: of1
  source:
    repoURL: https://github.com/dz1194/of1.git
    targetRevision: main
    path: open-project/manifests/grafana

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
