apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: of1-n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: of1
  source:
    repoURL: https://github.com/bee-corp/of1.git
    targetRevision: HEAD
    path: manifests/n8n

  destination:
    server: https://kubernetes.default.svc
    namespace: n8n

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 2m
