apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: of1-openproject
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: of1
  source:
    repoURL: https://github.com/dz1194/of1.git
    targetRevision: main
    path: open-project/manifests/openproject

  destination:
    server: https://kubernetes.default.svc
    namespace: openproject

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
