apiVersion: v1
kind: ConfigMap
metadata:
  name: openproject-env
  namespace: openproject
data:
  OPENPROJECT_HOST__NAME: "openproject.bee.vn"
  OPENPROJECT_HTTPS: "true"
  OPENPROJECT_DEFAULT__LANGUAGE: "vi"
  OPENPROJECT_RAILS__RELATIVE__URL__ROOT: ""
  RAILS_ENV: "production"
  OPENPROJECT_CACHE__MEMCACHE__SERVER: "memcached.openproject.svc.cluster.local:11211"
  OPENPROJECT_DISABLE__NOTIFICATION__EMAILS: "false"
  RAILS_MIN_THREADS: "4"
  RAILS_MAX_THREADS: "16"
  # Attachments lưu trên MinIO (S3-compatible)
  OPENPROJECT_ATTACHMENTS__STORAGE: "fog"
  OPENPROJECT_FOG__DIRECTORY: "openproject-attachments"
  OPENPROJECT_FOG__CREDENTIALS__PROVIDER: "AWS"
  OPENPROJECT_FOG__CREDENTIALS__ENDPOINT: "http://minio.minio.svc.cluster.local:9000"
  OPENPROJECT_FOG__CREDENTIALS__PATH__STYLE: "true"
  OPENPROJECT_FOG__CREDENTIALS__REGION: "us-east-1"
