apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-data
  namespace: openproject
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  storageClassName: longhorn
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 30Gi
