preUpgradeChecker:
  jobEnabled: false

defaultSettings:
  defaultReplicaCount: 2
  backupTarget: ""
  backupTargetCredentialSecret: ""

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2

longhornUI:
  replicas: 1

service:
  ui:
    type: NodePort
    nodePort: 30001

ingress:
  enabled: false
