replicaCount: 1

admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password

service:
  type: NodePort
  nodePort: 30008

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  storageClass: longhorn
  size: 5Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: OpenProject PostgreSQL
        type: postgres
        url: openproject-postgresql.openproject.svc.cluster.local:5432
        database: openproject
        user: grafana_ro
        secureJsonData:
          password: $__file{/etc/secrets/datasource/password}
        jsonData:
          sslmode: disable
          postgresVersion: 1400
          timescaledb: false
        editable: false

extraSecretMounts:
  - name: datasource-secret
    secretName: grafana-datasource-secret
    defaultMode: 0440
    mountPath: /etc/secrets/datasource
    readOnly: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: openproject-metrics
        orgId: 1
        folder: OpenProject
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/openproject
