replicaCount: 1

secret:
  existingSecret: n8n-secret
  existingSecretKey: N8N_ENCRYPTION_KEY

config:
  generic:
    timezone: Asia/Ho_Chi_Minh
  database:
    type: sqlite
  webhookUrl: http://192.168.1.100:30007   # ← đổi thành IP node của bạn

service:
  type: NodePort
  port: 5678
  nodePort: 30007

ingress:
  enabled: false

persistence:
  enabled: true
  storageClass: longhorn
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
