mode: standalone

existingSecret: minio-credentials

persistence:
  enabled: true
  storageClass: longhorn
  size: 50Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

buckets:
  - name: harbor-registry
    policy: none
    purge: false

# MinIO API (S3 endpoint) — port 30009
service:
  type: NodePort
  nodePort: 30009

# MinIO Console — port 30003
consoleService:
  type: NodePort
  nodePort: 30003

ingress:
  enabled: false

consoleIngress:
  enabled: false
