openproject:
  host: 192.168.110.101:30006
  https: false
  hsts: false

ingress:
  enabled: false

service:
  type: NodePort
  nodePort: 30006

environment:
  OPENPROJECT_EMAIL__DELIVERY__METHOD: smtp
  OPENPROJECT_SMTP__ADDRESS: smtp.bee.local
  OPENPROJECT_SMTP__PORT: "587"
  OPENPROJECT_SMTP__DOMAIN: bee.local
  OPENPROJECT_RAILS__MAX__THREADS: "16"

envFromSecret: openproject-env-secret

postgresql:
  enabled: true
  auth:
    existingSecret: openproject-postgresql
  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 20Gi
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 512Mi

web:
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1500m
      memory: 2Gi

worker:
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

persistence:
  enabled: true
  storageClass: longhorn
  size: 30Gi
